---
language: java
jdk:
  - openjdk7
before_script:
  - psql -c 'create database cla;' -U postgres
after_success:
  - "bundle install --binstubs"
  - "bin/cf target $TARGET"
  - "bin/cf login --username $USERNAME --password $PASSWORD --organization $ORGANIZATION --space $SPACE"
  - "bin/cf push"
env:
  global:
    - "DATABASE_URL=postgresql://travis@127.0.0.1:5432/cla"
    - "TARGET=https://api.run.pivotal.io"
    -
      secure: dANRJpQd732qufZCwD4wPHeK7BbT5YtmWGh/wl0VWt7Y63TnZT3C595g2IfIXv+ZgznQJh4MMWk3UZ/rY8i9Yp7dNxn9+BjlubhzeFWTvuhGZB8RtHrmQQGBuKQZOjE9PH4Dr52IPMnCyNqEek8nE1Z4rKLABdR+uex24Zgn8rY= # $USERNAME
    -
      secure: WYgGOVS1jjuZ5RquByMDwm5MYqcT2YWTyFt89g1Jp/icKmE4Sq2mx2AJNrY1OlAPZSLuVZ0olfzvBj+mIqo7Jy/6qc96Fzr/E71Hz2N5euaw6dtVhwvfFqXmT4pqnsUwfrqBmNOglIt225ptZIzDD4m6GcITovsLT2+RPuECaq0= # $PASSWORD
    -
      secure: LQVV+/QIOgwaFnDZJ5S3jgMz5OtVgid/7XkTN3H7K3S8c2Z65JUT3wwDJ/r2emQ/eeQmGEOl4qJo5zuAguDswZ8FbVUJhFiUeUSfgD8fobal/C8zyhRJEnrJ3WYDCcxbFXL8QfKbVly2NIckP6AO4w8MlnJJnPZ1kj7mCVSiFlU= # $ORGANIZATION
    -
      secure: RoS/2hXSU0lkgNSnSXzMhGx2t4qJA9SCOe0JAXJjveloRU/Xx7WGXYSwTglrIqCgi3wwMMbCYO9fTu0zeJx7yse/LO2s1ltOhsW1pZgSPpeIhgVL7Q6cDiwMYrm++a/pLI+0c+3RtJz1kbG2yvO4NyY0t/nO6BEtD04i4Y8fYZg= # $SPACE
