---
language: java
jdk:
  - openjdk7
before_script:
  - psql -c 'create database cla;' -U postgres
after_success: |
  if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_SECURE_ENV_VARS == 'true' ]] ; then
    bundle install --binstubs
    bin/cf target $TARGET
    bin/cf login --username $USERNAME --password $PASSWORD --organization $ORGANIZATION --space $SPACE
    bin/cf push
  fi
env:
  global:
    - "DATABASE_URL=postgresql://travis@127.0.0.1:5432/cla"
    - "ENCRYPTION_KEY='OAI]TQ(aYvcyUMwzGpKh7HptueVQJPkCVSYjxpOOSZeVby4FWP'" # This is a test-only value
    -
      secure: G55DG5X1TGteGNeo8NNyONXrbBsLEvXH4v2K2XjEc7Xza2JNYzsPTLAhSezcuOJlF7jD2rtlE+dX1yo+g8NlXCX/JekURcs6eLl3mh9Qunf4kCekOwiN5NaUcYCm9lN5aUkZb5NjRULfbzdCqt8gTJ3qZANHMR+HK/aLpDrq4TQ= # $USERNAME
    -
      secure: QTMF1ucNHsjTNCkYgfE7wGnK3vHNDl2tyhllRnI8xg+TpiI9x6TcVqLhzwazNlpdUbjHjtsA7zFEL6vwMxV+UUTydBWRecDAqT1cpoRDZ7zgcr4i+SQtvazuBtPDOBsvHslodGzRksfbH3IC6+OXZb7b+5SIbHTxNVAbyhrykiY= # $PASSWORD
    -
      secure: UNVIZRL57MaFoPYLwwsemSvZi+T/gg+SlR+RLEBngpi5MXhXUEXhL7S+gAOj6V6otDj9Af8hG41+qEwGDVKMOjyCnjAPmiVzgUJgmBXO2lcB0G42nPfPyGI1mMTwqdHQoCh0meevcnutQ+l3Hi9jD5RI+ETJvXF309eUlYfhMK0= # $ORGANIZATION
    -
      secure: EynJa+7llSrdMAfa0QoQr6zGYngbSgOEYRlnP+IJXpFEG+xBFwUFeZjYzhrvmhhYvhztxo5oLCLTETyubq9N55G8Kesbnm9zjczlhhmBlzmgSWaqgdw037Vjoo+cwO+2k8XYsDIATAB1iEw17n6rhftCq7TCkObUQnc6pq7VER0= # $SPACE
    -
      secure: f15vVG6JR6Gsh21pFh1ZY6KmCwbrZLImCYzljNAh7kwsgw0+FA7ynHK7CsDC7K+pYY/NOMwsoyhKTiWgiVa6WcgfTSYG+0nBeRUNxf4EfF45xqUV8H0Nbe4EB1lrEne+BVYtfU8LFmlMvJ7w6FGAvc8WgnQx+8JnkvzkmoddaXg= # $TARGET
