---
language: java
jdk:
  - openjdk7
before_script:
  - psql -c 'create database cla;' -U postgres
after_success:
  - "bundle install --binstubs"
  - "bin/cf target $TARGET"
  - "bin/cf login --username $USERNAME --password $PASSWORD --organization $ORGANIZATION --space $SPACE"
  - "bin/cf push"
env:
  global:
    - "DATABASE_URL=postgresql://travis@127.0.0.1:5432/cla"
    - "ENCRYPTION_KEY='OAI]TQ(aYvcyUMwzGpKh7HptueVQJPkCVSYjxpOOSZeVby4FWP'" # This is a test-only value
    -
      secure: KmU5dVk9w6lNZvDlKLlUd8Sse33JZgvMaG1msp0l2SG1HSlFqxwo9Gc6vUbJlgZT6VaICKmsFAfHZQaji3sqVQ3plhztYynQGuKz0wyE11B+JYeodADz+rAU9esAxpnenl9xhp+mdWv1sgqbkTtcxqc9CDMNKprb0mWbfPb+wfc= # $USERNAME
    -
      secure: bnk7xbaeLmVpuWrW/8f4g8DOz/Vi2J7QYdPBvk0wnWb1BrYC7X92az/8ev6n27iGb9yX3bfbfb/J7XMMul9AlbJybAsFmH5KyPduKZ4hXikXKPEsbnWpIxN8A6TUxnnlYX0NYLu3cFNc7m6Xv6upYrFGjGpau0DQG7135ofXhwo= # $PASSWORD
    -
      secure: Z3i6GJXCWQrsD343fJk7rv7hm2XKZEIGKFFPF0XPz2xT/Jqirx9Fiwl8odm48jG6G8yBMyk34AgJkjPTf28vK59v+/8eLueqGbPaZrJtZEvuGdEeLGT3UpvXdzOjwZbPspFFYgXAb6NHn2HpgtLQ2RvIjTXG4iRfUJ41+OoQ9wc= # $ORGANIZATION
    -
      secure: B8w6l+idADvjwVNDsifbyb3xpjILaf8B9ftRunBMaane/AuXtY3NUOBX5Qxzes4qkvq2IqG04/YAVyvNJE2MYuSSDcaU809hkOX5iJqC/fgrgprV/5oO+5fTUKNh/d+GYI6SX5s5WH8DSFHTMLUCQ+omBMs3AoXNZ1ykW/GKoa4= # $SPACE
    -
      secure: B/E5TQUpgwNterNTAG9Q9fOOw1up8ffhTTsFx8EU0SbPz11FxX1eMM19lHMmGKpDwzscyzU22htrN4ZkaIA2yTxkUaHPQZpVKJDj6/3lgR8f5D9Zfm66HDzuYiaf/EQBxxM4ha3FKjSPzQa2M8ED0Tm27dZgq0WAC3LWAFMG6kw= # $TARGET
branches:
  only:
    - master
