---
language: java
jdk:
  - openjdk7
after_success:
  - "bundle install --binstubs"
  - "bin/cf target $TARGET"
  - "bin/cf login --username $USERNAME --password $PASSWORD --organization $ORGANIZATION --space $SPACE"
  - "bin/cf push"
env:
  global:
    - "TARGET=https://api.run.pivotal.io"
    -
      secure: dANRJpQd732qufZCwD4wPHeK7BbT5YtmWGh/wl0VWt7Y63TnZT3C595g2IfIXv+ZgznQJh4MMWk3UZ/rY8i9Yp7dNxn9+BjlubhzeFWTvuhGZB8RtHrmQQGBuKQZOjE9PH4Dr52IPMnCyNqEek8nE1Z4rKLABdR+uex24Zgn8rY= # $USERNAME
    -
      secure: Uis+6fkHujQ3s31XvN0H9s0jgK34pqpU9VqtbOHpaqYmNFCpWuZSfRc7g39mqjjfxbz0LrGZLBD/lePonWY9j8XrwzDDqm/LVSx07HGKEh3unuV6vbiIZ2B6YA8te6O92EkSkbo4AWTBKRB6JNXWv1FwpWzVi22gaxzpaFXIOIs= # $PASSWORD
    -
      secure: LQVV+/QIOgwaFnDZJ5S3jgMz5OtVgid/7XkTN3H7K3S8c2Z65JUT3wwDJ/r2emQ/eeQmGEOl4qJo5zuAguDswZ8FbVUJhFiUeUSfgD8fobal/C8zyhRJEnrJ3WYDCcxbFXL8QfKbVly2NIckP6AO4w8MlnJJnPZ1kj7mCVSiFlU= # $ORGANIZATION
    -
      secure: RoS/2hXSU0lkgNSnSXzMhGx2t4qJA9SCOe0JAXJjveloRU/Xx7WGXYSwTglrIqCgi3wwMMbCYO9fTu0zeJx7yse/LO2s1ltOhsW1pZgSPpeIhgVL7Q6cDiwMYrm++a/pLI+0c+3RtJz1kbG2yvO4NyY0t/nO6BEtD04i4Y8fYZg= # $SPACE
