---
security:
  basic:
    enabled: false
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:build_monitor;MODE=PostgreSQL
  jpa:
    hibernate.ddl-auto: none
    show_sql: false

---
spring:
  profiles: local
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost/github_cla_integration
    username: ${user.name}
